# Generated by Django 4.1.4 on 2022-12-20 13:08

from django.db import migrations, models
import django.db.models.deletion
import main_page_cafe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('is_visible', models.BooleanField(default=True)),
                ('video', models.FileField(blank=True, upload_to=main_page_cafe.models.Description.get_file_name)),
            ],
            bases=(models.Model, main_page_cafe.models.Import_file),
        ),
        migrations.CreateModel(
            name='Description_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to=main_page_cafe.models.Events.get_file_name)),
            ],
            bases=(models.Model, main_page_cafe.models.Import_file),
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveIntegerField(unique=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page_cafe.events')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ingredients', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=main_page_cafe.models.Dish.get_file_name)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page_cafe.dishcategory')),
            ],
            bases=(models.Model, main_page_cafe.models.Import_file),
        ),
    ]
