# Generated by Django 4.1.4 on 2022-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description1',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
