# Generated by Django 4.1.4 on 2022-12-23 11:53

from django.db import migrations, models
import main_page_cafe.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_cafe', '0002_description_description1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page_cafe.models.Galery.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=100)),
            ],
            bases=(models.Model, main_page_cafe.models.Import_file),
        ),
    ]
