# Generated by Django 4.1.4 on 2022-12-23 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_cafe', '0003_galery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Не вірний формат електроної адреси', regex='^[0-9a-zA-Z-_]+@\\w+(.\\w)*$')])),
                ('phone_num', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Не вірний формат номера', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[- ]?){7}$')])),
                ('persons', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('manager_date_processed', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AlterField(
            model_name='galery',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
     ]

