# Generated by Django 4.1.4 on 2022-12-25 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_page_cafe.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_cafe', '0004_book_table_alter_galery_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=main_page_cafe.models.Chefs.get_file_name)),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
            ],
            bases=(models.Model, main_page_cafe.models.Import_file),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_open', models.CharField(max_length=200)),
                ('hours_open', models.TimeField()),
                ('hours_close', models.TimeField()),
                ('is_visible', models.BooleanField(default=True)),
                ('map', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('manager_date_processed', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to=main_page_cafe.models.Testimonials.get_file_name)),
                ('feedback', models.TextField(max_length=300)),
                ('mark', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            bases=(models.Model, main_page_cafe.models.Import_file),
        ),
        migrations.CreateModel(
            name='Phone_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Не вірний формат номера', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[- ]?){7}$')])),
                ('is_visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page_cafe.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Email_adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page_cafe.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('is_visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page_cafe.contacts')),
            ],
        ),
    ]
