# Generated by Django 4.1.4 on 2022-12-26 09:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_cafe', '0005_chefs_contacts_contacts_us_testimonials_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_table_F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=100)),
                ('phone_num', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Не вірний формат номера', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[- ]?){7}$')])),
                ('persons', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('manager_date_processed', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Book_table',
        ),
    ]
