# Generated by Django 4.1.4 on 2022-12-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_cafe', '0006_book_table_f_delete_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_table_f',
            options={'ordering': ('date',)},
        ),
    ]
